apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  annotations: {}
  name: mongodb-operator
  namespace: flux-system
spec:
  chart:
    spec:
      chart: community-operator
      sourceRef:
        kind: HelmRepository
        name: mongodb
      version: 0.7.2
  install:
    createNamespace: true
    disableWait: false
    remediation:
      retries: -1
  interval: 5m
  releaseName: mongodb-operator
  storageNamespace: mongodb-operator
  targetNamespace: mongodb-operator
  values:
    operator:
      watchNamespace: "*"
    namespace: mongodb-operator
    createResource: false